### ISSUE TITLE
parsing errors 

### ISSUE THREAD

**Issue by kinfinity** [lal12/proto-parse#1]
Very nice tool you've written but it doesn't seem to parse files which have comments in them properly

**Comment by lal12** [comment]
I made a small fix, I did some testing and it seems to work. Please use the current git master for your proto files, to check if it now works properly. Afterwards I will tag it and publish it as 0.0.4 on npm.

**Comment by kinfinity** [comment]
it works perfectly fine ... but if you could add a little more work into handling the [ require , optional ] keywords as in the example bellow it'd be even better... your work saved me tons... very much appreciated.
`message User{
      required string name = 1;
      optional string nickname = 2;
      required string gender = 3;
}`

**Comment by lal12** [comment]
I think this is actually proto 2 syntax, but this module actually only supports proto 3 syntax. 

I actually planned on adding support for proto 2 originally, but since I am not using this module any more, I currently don't have any plans to implement it. As far as I remember there are more differences than the `required` and `optional` keywords.

You could look up the differences between proto2 and proto3 and provide me with a list of difference then I could decide how much work it is and whether I could to do that. However if you doing it, create another issue, since this one is about a bug regarding the comment parsing.

**Comment by kinfinity** [comment]
Good day.. I think you can just push it like that for now... because i noticed the [require, optional] aren't really need because it behaves the same way if they aren't set. Thanks

**Comment by lal12** [comment]
Pushed v0.0.4 to github and npm.

**Comment by kinfinity** [comment]
Thanks so much friend... 👍
